### ISSUE TITLE
Figure size

### ISSUE THREAD

**Issue by Pakillo** [PJordano-Lab/R-figures#1]
He puesto todas las figuras con el mismo ancho (400 px). Va bien así, o lo subo a 500?
En mi opinión no hace falta que se vean muy grandes, esto es solo un thumbnail para que el que esté interesado pinche y vea los detalles... Pero lo que digáis
Gracias

**Comment by pedroj** [comment]
Las dejaría a 400 px. Eso también encaja mejor las figuras en la página.

**Comment by nestorperez** [comment]
Yo lo veo de lujo así, a 400 px,
yo puedo subir el código que usé para plotear los eventos de dispersión (también vale para eventos de mating) con la función curvedarrow (diagram package) que adapté de un código de Pedro para mis datos y otra script similar con la función arrows (del paquete básico de R).

Por cierto ya me respondieron de github y me dieron una cuenta "Micro Plan” por dos años. 

Abrazos,

Néstor

**Comment by nestorperez** [comment]
Yo lo veo de lujo así, a 400 px,
yo puedo subir el código que usé para plotear los eventos de dispersión (también vale para eventos de mating) con la función curvedarrow (diagram package) que adapté de un código de Pedro para mis datos y otra script similar con la función arrows (del paquete básico de R).

Por cierto ya me respondieron de github y me dieron una cuenta "Micro Plan” por dos años.

**Comment by Pakillo** [comment]
Estupendo. Gracias!
